### ISSUE TITLE
Feature request: (Host-specific) remote command prefix

### ISSUE THREAD

**Issue by pbsds** [remote-cli/remote#49]
When working on various remote hosts, it would be nice to prefix the `remote COMMAND` with something. This could either because the remote is shared, warranting prefixing all command with `nice -n 5`, or because the command needs to run inside some docker container with `docker run`, or because it has to queued in some job system such as SLURM.

Specifically, the command [here](https://github.com/remote-cli/remote/blob/master/src/remote/workspace.py#L131) would be nice to if it could be prefixed.

One way this could be configured in `.remotes.toml` would be:

```toml
[general]
cmd_prefix = ["nice", "-n", "5"]

[[hosts]]
host = "..."
cmd_prefix = ["docker", "run", "-it", "MYIMAGE", "-v", "/some/folder:/some/path"]

[[hosts]]
host = "..."
cmd_prefix = ["srun", "--account=foobar", "--mem=4g", "--cpus-per-task=4"]

[[hosts]]
host = "..."
cmd_prefix = [] # no prefix, ignores the default in [general]
```

This way enables you to have both a default prefix, with the option to override it per remote host
